### ISSUE TITLE
Implement the list screen

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/resume-author#10]
Implement the list screen just like Linkedclaims author.The list screen will display a list of completed or in progress resumes.

**Comment by 0marSalah** [comment]
yeah so to display the resumes we should upload some first

so here is my thoughts about file structure on users drive:

Resumes/
     Completed/ ...signedResumes
     NonCompleted/ ...unsignedResume or sessions

**Comment by 0marSalah** [comment]
so the thing is we dont have the final schema to sign the resume (currently we have the self-asserted skill VC),

i think the work will start on @cooperation/vc-storage package as follow:
- ResumeHandler instance or class
     - genearte the unsinged credential resume (convert the raw data from coming from ResumeAuthor to Unsinged Credential) like i did here on [generateUnsignedVC](https://github.com/Cooperation-org/linked-claims-storage/blob/main/src/utils/credential.ts) method in vc-storage package
     - sign the generated unsigned credential
     - verify method
 - Update Google Drive with new method to get all resumes [signed & non-signed resumes]

**Comment by 0marSalah** [comment]
maybe we should change the task name to be more related like "handle resume in users google drive).
