### ISSUE TITLE
Implement import page

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/resume-author#14]
Create the Ui for the import selection page 
We left out the continue button at the moment intentionally.
removed the continue button due to its inconvenience
![Image](https://github.com/user-attachments/assets/ebb79b92-2737-4352-8422-c22c8ee7d13d)

**Comment by Gitongamiriam** [comment]
https://www.figma.com/design/RrPCGPQ1bCbQ6YTQFMHM2x/Resume-Author-Examples?node-id=13-575&t=mHLqqNHe6NdAeHdL-1

Here is the Figma file for the design 
The design changes are still in progress
@AmrNabel demonstrated it on the Wednesday call

**Comment by AmrNabel** [comment]
![Image](https://github.com/user-attachments/assets/d1aaf5c4-1d5d-4f9b-973b-702b385a4e9c)
removed the continue section the import page

**Comment by AmrNabel** [comment]
implemented the import page and make the card of import from likedin is the signing button to sign in with it
