### ISSUE TITLE
Import skill credential created in LinkedClaims Author

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/resume-author#23]
Imported credentials should show up in the skill section of the Resume Author.
In addition display these credentials on the imported credential library on the right side bar.(At the moment just display there names on the side bar no other action)

**Comment by AmrNabel** [comment]
now I get the data from drive and get the access token to fetch and show the valid credentials on the right sidebar as you can see on the pic

** that is not the final design it is only for the functionality 

![Image](https://github.com/user-attachments/assets/6a828702-6d18-4eed-9892-8704afc9bf72)

**Comment by Gitongamiriam** [comment]
Demo on the call
