### ISSUE TITLE
Implement Add work experience item

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/resume-author#25]
In the work experience section of the resume user can click the add button, and edit the fields that match the experience vc from the engineering document. [ Employment History Example ](https://docs.google.com/document/d/1GrFyUNcezHQ0qMKHQwxBFpVt9q5iv7og2EBSHGlq_fA/edit?tab=t.0#heading=h.2c7svqrnejyo)

**Comment by dev-mhany** [comment]
![لقطة شاشة 2024-12-26 131405](https://github.com/user-attachments/assets/e84f9ad6-d3be-4943-8242-feb816c65dd4)
![لقطة شاشة 2024-12-26 131324](https://github.com/user-attachments/assets/9f8c1e3d-caed-4151-b1dc-11780cc3c991)
![لقطة شاشة 2024-12-26 131057](https://github.com/user-attachments/assets/fb788043-32dc-4239-a385-d236f12bd4e9)

**Comment by Gitongamiriam** [comment]
Demo on the Monday call.
