### ISSUE TITLE
Add narrative text box to each section of the resume

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/resume-author#41]
Add a narrative field and a rich text editor to each section 
See the summary section from screenshot below for an example.![Image](https://github.com/user-attachments/assets/1ce396d2-83ad-4dae-808e-e9f1060db9a2)

**Comment by dev-mhany** [comment]
![Image](https://github.com/user-attachments/assets/5dc37d1f-8456-407a-8aef-edd60ec8ab50)
Omar already made it so I'll just make it a **rich** text editor

**Comment by dev-mhany** [comment]
![Image](https://github.com/user-attachments/assets/e53d6244-8fde-4850-9502-6ae063e83814)
![Image](https://github.com/user-attachments/assets/10e6e9f2-759e-4942-9e30-1433c2a9d941)
